services:
  postgres:
    image: postgres:16
    container_name: db_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: meeting
      TZ: UTC
      PGTZ: UTC
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - meeting-networks

volumes:
  postgres_data:

networks:
  meeting-networks:
    driver: bridge